---
language: ruby
bundler_args: "--without development system_tests"
script: "bundle exec rake test"
before_install: "rm Gemfile.lock || true"
notifications:
  email: false
sudo: false
rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - 1.8.7
