name          'waveclaw-transmission_daemon'
version       '0.1.0'
source        'https://build.opensuse.org/project/show/home:ghostlyrat'
author        'waveclaw'
license       'Apache 2.0'
summary       'Deploy the daemonized transmission service.'
description   ''
project_page  'https://github.com/waveclaw/transmission_daemon'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/apt'
dependency 'puppet/zypprepo'
